version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g create-react-app
      - npm install
      - npm start
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'